Feat/signin/signup
savicsoft/mvp-experiment-client pull request #13
Opened 2023-11-07 19:35 UTC by Ben2oid

Added the signup and signin functionality to the page

2023-11-07 19:38 UTC, Ben2oid commented
I'm having the conflicts because I have added react hook form to the dev. Is there a way to merge this anyways? We still haven't added react query to it either tho...

2023-11-07 19:38 UTC, MilosIl commented on src/hooks/useGeoLoc.tsx
> +type LocationData = {
Make a new file for type LocationData, LocationData.d.ts and make an import

2023-11-07 19:45 UTC, MilosIl commented on src/pages/Login.tsx
> +type Inputs = {
make new file. Inputs.d.ts for type

2023-11-07 20:09 UTC, MilosIl commented on src/pages/Login.tsx
> +      <input
should use our component, but doesn't understand why it doesn't show in components folder like in dev branch

2023-11-07 20:10 UTC, MilosIl commented on src/pages/SignUp.tsx
> +type Inputs = {
Import from Inputs.d.ts

2023-11-07 20:15 UTC, MilosIl requested changes
To use input component, that is made.

Good work!

2023-11-08 11:28 UTC, MilosIl commented on src/hooks/useGeoLoc.tsx
> +  function success(pos: any) {
I think that type for pos should be "LocationData". Because pos.cords are actually longitude and latitude

2023-11-08 11:31 UTC, MilosIl approved these changes
Keep up good work!

2023-11-08 20:00 UTC, nikaakin commented on src/pages/SignUp.tsx
> +import { Button } from '@/components/Button';
import should be @/components. (if  this way is not possible Button is not exported in all index.ts)

2023-11-08 20:01 UTC, nikaakin commented on src/pages/SignUp.tsx
> +import { Inputs } from './type';
Please give type names that would end with "Type", like in this case InputsType. This is geenrally how you will see most people do it

2023-11-08 20:05 UTC, nikaakin commented on src/pages/SignUp.tsx
> +  const checkPassword = (value: string) => {
All this logic in this case is not neccessary to do it here. Problem is that this is sign up and you need somewhat same logic for sign in and maybe in another place afterwards. So best is to make Schemas like here https://github.com/nikaakin/movie-quotes-front/tree/main/schema. Zod give most of the stuff you will need. Ask in chat If you cant. Otherwise if the validaiton logic is very form specific only then make validation rules in components itself

2023-11-08 20:07 UTC, nikaakin commented on src/pages/SignUp.tsx
> +    register,
Any kind of logic (other then jsx) should be in custom hook called useSignup.ts. make the hook and import the stuff you need for UI.  Put custom hook and component in Pages/SignUp/ inside this.

2023-11-08 20:10 UTC, nikaakin commented on src/pages/SignUp.tsx
> +          pattern: { value: /^\S+@\S+\.\S+$/, message: 'Invalid email' },
this is not neccessary as well if we will use zod. https://github.com/nikaakin/movie-quotes-front/blob/93d735c651d96c85a69abc587b310dc499590f15/components/Profile/useProfile.ts#L46 . this  is how you connect zod and react hook form to each other. and make sure schemas you make match the names of registered inputs and validation will apply automatically

2023-11-08 20:11 UTC, nikaakin commented on src/pages/SignUp.tsx
> +          pattern: { value: /^\S+@\S+\.\S+$/, message: 'Invalid email' },
there are same stuff in this file. I'm not going to add comment on every one but lets separate logic like I said in precious comment

2023-11-08 20:12 UTC, nikaakin commented on src/pages/Login.tsx
> +import { Button } from '@/components/Button';
Import should be @/components

2023-11-08 20:18 UTC, nikaakin commented on src/context/contextProvider.tsx
> +import { useState } from 'react';
we dont need context please remove. If you need to store state use react query. First you import useQueryClient and that one will have getqyeryData and setQueryData use that as state management if you need it.

2023-11-08 20:21 UTC, nikaakin commented on src/hooks/type.d.ts
> +export type LocationData = {
LocationDataType plese name types these way, its easier to understand what going on when you seen them imported afterwards

2023-11-08 20:22 UTC, nikaakin commented on src/hooks/useGeoLoc.tsx
> +  function success(pos: any) {
Try to use "any" type any cost. using any make pointless to use typescript, so try to avoid. In this case I think as milos said LocationDataType would be better

2023-11-08 20:24 UTC, nikaakin commented on src/pages/GuestView.tsx
> +  if (token) {
for now this kind of logic is not developed so please remove it.

2023-11-08 20:25 UTC, nikaakin requested changes
#

2023-11-09 11:34 UTC, Ben2oid commented on src/hooks/useGeoLoc.tsx
> +  function success(pos: any) {
unfortunately if I only add LocationDataType it will still mark it as a not matching value. I added LocatioDatatype | any now and it won't mark it that way now.

2023-11-09 11:39 UTC, Ben2oid commented on src/pages/Login.tsx
> +import { Button } from '@/components/Button';
since in the components there is a folder Button and in the folder is the index.ts, I think it's going to be like this. Unless we start collecting the components' location data in an index.ts file outside of their assigned folder.

right now this is how the folder structure is:
![image](https://github.com/savicsoft/mvp-experiment-client/assets/114087987/2a02137c-9e58-44a8-bfa0-2030bdae8d6a)

2023-11-09 11:40 UTC, Ben2oid commented on src/pages/SignUp.tsx
> +import { Button } from '@/components/Button';
Oh I see, you have to structure it all the way down then. Did that and now it looks like that.

2023-11-10 04:30 UTC, nikaakin commented on src/hooks/useGeoLoc.tsx
> +  function success(pos: any) {
Dont add LocationDateType | any as well. This is not locationDataType. It has coords inside that you are accessing. So you can give  { coords: LocationDataType}  as a type.

2023-11-10 04:33 UTC, nikaakin requested changes
#

2023-11-15 18:38 UTC, Ben2oid commented on src/hooks/useGeoLoc.tsx
> +  function success(pos: any) {
Solved it

2023-11-17 03:06 UTC, nikaakin requested changes

2023-11-17 03:06 UTC, nikaakin commented on src/pages/GuestView.tsx
> +  const { data } = useAxios();
This hook is not neccessary we have no controll over it. It always will be sent on 1 enpoint. If you want to still make this hook give arguments so we will have more controll over it and also return some more values that we know the state of the fetching and data. Isloading, isFetched, isError  are something we will probably need.

2023-11-17 03:06 UTC, nikaakin commented on src/pages/SignUp.tsx
> +        onChange={(e) => {
this is not neccessary with zod

2023-11-17 03:06 UTC, nikaakin commented on src/pages/SignUp.tsx
> +  const { checkPassValidator, checkPassword, submit } = usePasswordLogic({
put logic in the local hook useSignUp

2023-11-17 03:06 UTC, nikaakin commented on src/pages/SignUp.tsx
> +  const { checkPassValidator, checkPassword, submit } = usePasswordLogic({
usePassworkLogic hook is not neccessary with zod

2023-11-17 07:56 UTC, Ben2oid commented on src/context/useAxios.tsx
> +export const useAxios = () => {
Not totally sure what you meant. I just made the useAxios reusable for now. The key and the url needs to be input now to be used.

2023-11-17 08:11 UTC, Ben2oid commented on src/context/useCountdownToLogin.tsx
> +  setTimeout(() => {
right now it has no functionality, and it wasn't used in the code. I did something similar in the default and guest view that I wanted to replace with this hook. But did not implement it yet.

2023-11-17 10:10 UTC, nikaakin commented on src/context/useCountdownToLogin.tsx
> +  setTimeout(() => {
I think I commented on that one too in DefaultView. So what I meant is if we are navigating someone we shouldn't make them wait. Thats why I didn't think this was neccessary. Other then waiting we can just use useNavigation hook when we need it. Again if you think this is important to have please just text in chat or somewhere so we know what you meant by doing this and what plans you have with this.

2023-11-17 10:16 UTC, nikaakin commented on src/context/useAxios.tsx
> +export const useAxios = () => {
So problem with is that if we want put patch or delete we have to make separate hook for those. That would be too much encapsuling. So that why I introduced services folder https://github.com/nikaakin/movie-quotes-front/blob/main/services/authServices.ts with enpoints inside. useQuery and useMutation are already good enough hooks so I dont think we would need any encapsuling to add some attributes. If you dont agree with this please type in chat so others can decide because I think this kind of hook is not neccessary

2023-11-17 10:22 UTC, nikaakin commented on src/context/useAxios.tsx
> +export const useAxios = () => {
axios.get, axios.put(). I was referring those

2023-11-17 10:25 UTC, Ben2oid commented on src/context/useAxios.tsx
> +export const useAxios = () => {
I'm totally fine doing it your way, just it still puzzles me how the whole structure of the code is going to look like. The reason I created useAxios is so I have a palceholder to test the form. It is definitely not the standard that I want to build on. So should I rather create this authServices hook instead and useAxios there? I think we should make a session and talk it over while you or I share the screen and look at the whole code at hand. Once the structure of the project is built up correctly, I think it will be way easier to approach the whole thing.

2023-11-17 15:47 UTC, nikaakin approved these changes

2023-11-17 15:47 UTC, merged