Sign in
savicsoft/mvp-experiment-client pull request #15
Opened 2024-01-31 17:41 UTC by Ben2oid

2024-01-31 19:12 UTC, nikaakin commented on src/pages/GuestView/GuestView.tsx
> +      {/*       <div className='text'>GuestView</div> */}
lets try not leave any commenets it could get confusing as we go on

2024-01-31 19:12 UTC, nikaakin commented on src/styles/styles.css
> +  padding: auto;
putting every style in style.css will make this file very big in future so if we want to write styles like this we should split this code accordingly, like there is .btn class and that could be in styles/components/button.css file. Otherwise we could use tilewind or material ui with its own styles. we should discuss this with rest of them on friday because we dont want to have styles everywhere lets try to stick with one approach

2024-01-31 21:37 UTC, MilosIl commented on src/styles/styles.css
> +  padding: auto;
I agree with you, that we need split css in smaller files. But for now its look good to me. We can discuss and decide how are we going to write css in future.

2024-01-31 21:44 UTC, MilosIl commented on index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@500&family=Jomhuria&family=Nunito:wght@300&family=Roboto:wght@100&display=swap" rel="stylesheet">
We don't use for "nuntio" or "roboto". From figma file from what I can see we use "jomhuria" and "roboto condensed". It in frame "ui-kit". Inter font is used for wireframes, but we should use from "in design"

2024-01-31 21:47 UTC, MilosIl commented on src/pages/Login/Login.tsx
> +                  alt=''
use file name as alt tag for now. alt="email" or alt="email-icon"

2024-01-31 21:50 UTC, MilosIl approved these changes
It's good work. Use guidelines that our designers left us in figma file. We should make it according to their design.

2024-02-06 16:57 UTC, MilosIl requested changes

2024-02-06 16:57 UTC, MilosIl commented on src/styles.css
in this file should be only first three lines, rest should be deleted

2024-02-06 16:58 UTC, MilosIl commented on src/styles/styles.css
this file should be removed

2024-02-06 16:59 UTC, MilosIl commented on src/pages/Login/Login.tsx
change h1 style, to tailwind classes

2024-02-06 17:27 UTC, MilosIl commented on tailwind.config.js
do not understand changes.. We are not going to use mdx or it wasn't talked about that.

2024-02-06 17:29 UTC, MilosIl requested changes
Try to use, default tailwind values for example px-3, w-96. 

Remove unused css in src/styles.css

2024-02-06 20:58 UTC, Ben2oid commented on src/styles/styles.css
It is removed. :D That's why it showed up. It states that the whole styles document was deleted.

2024-02-06 20:59 UTC, Ben2oid commented on tailwind.config.js
if I understood the documentation well, the one that I have input is needed if the global.css file is within in the src document.

2024-02-06 21:02 UTC, Ben2oid commented on tailwind.config.js
I think I read a different documentation of Tailwind and this was what it asked to use. fixed it now.

2024-02-07 16:10 UTC, MilosIl approved these changes
Nice work!

I didn't understand why in Login page are lines 79 and 93 are written like that, but that also works :)

2024-02-07 18:18 UTC, nikaakin approved these changes

2024-02-07 18:18 UTC, merged