Display rides
savicsoft/mvp-experiment-client pull request #25
Opened 2024-02-19 19:50 UTC by MilosIl

Page display rides it's almost over, since their will be some changes I need some advice on how to improve code.

Passengers component needs to be absolute on select(dropdown). Don't know how to replace arrow with icon

Page isn't mobile responsive, so some width maybe are "broken" if so. please comment or give me a suggestion how to fix it.

2024-02-21 20:28 UTC, Ben2oid requested changes

2024-02-22 02:51 UTC, nikaakin commented on src/Icons/MinusIcon.tsx
> +        stroke-width='2'
raect will give you warning for any prop tha has '-' inside you can check console. instead of '-' you can start another word with capital letter

2024-02-22 02:51 UTC, nikaakin commented on src/Icons/PlusIcon.tsx
> +        stroke-linecap='round'
same here '-'

2024-02-22 02:51 UTC, nikaakin commented on src/components/HeaderSearchBar/HeaderSearchBar.tsx
> +import { PlusIcon } from '@/Icons/PlusIcon';
@/icons put these 3  icons into one import

2024-02-22 02:55 UTC, nikaakin commented
This pull request has code about display rides and header as well and for those you added some types, schemas, styles and logic. For future only include something else as well in the pull request if that will not be a big change. This will be good for review process as well as for in future if we want to know where we changed something about header. This is a little note for future otherwise great work!

2024-02-26 10:14 UTC, MilosIl commented on src/components/HeaderSearchBar/HeaderSearchBar.tsx
> +            <PersonAddIcon />
fixed, did work around that

2024-02-26 10:15 UTC, MilosIl commented on src/components/HeaderSearchBar/HeaderSearchBar.tsx
> +                <button onClick={() => handleRemovePassengers('children')}>
Putted disabled if passengers are 0

2024-02-26 10:15 UTC, MilosIl commented on src/Icons/MinusIcon.tsx
> +        stroke-width='2'
fixed

2024-02-26 10:15 UTC, MilosIl commented on src/Icons/PlusIcon.tsx
> +        stroke-linecap='round'
fixed

2024-02-26 10:21 UTC, nikaakin approved these changes

2024-02-27 10:34 UTC, Ben2oid approved these changes

2024-03-03 15:40 UTC, nikaakin approved these changes

2024-03-03 15:42 UTC, nikaakin requested changes

2024-03-03 15:42 UTC, nikaakin commented on src/components/HeaderSearchBar/HeaderSearchBar.tsx
> +            onClick={handleSubmit(onSubmit)}
please read my comment about how to handle form submition and fix this. also verify that you are receiving all the data from the form the way you are supposed to

2024-03-03 15:43 UTC, nikaakin commented on src/components/HeaderSearchBar/HeaderSearchBar.tsx
> +            onClick={handleSubmit(onSubmit)}
https://github.com/savicsoft/mvp-experiment-client/pull/25#issuecomment-1963807187

2024-03-07 20:15 UTC, MilosIl commented
is it better  now?

2024-03-07 21:19 UTC, nikaakin approved these changes

2024-03-07 21:20 UTC, nikaakin commented
Now it seems fine. Great work

2024-03-07 21:20 UTC, merged